# Relaxed.Ruby.Style

AllCops:
  Exclude:
    - '*.gemspec'
    - 'bin/*'
    - 'Gemfile*'
    - 'spec/dummy/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.3

inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

# Sometimes I believe this reads better
# This also causes spacing issues on multi-line fixes
Style/BracesAroundHashParameters:
  Enabled: false

# We use class vars and will have to continue doing so for compatability
Style/ClassVars:
  Enabled: false

# We need these names for backwards compatability
Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

# This has been used for customization
Style/MutableConstant:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Performance/Count:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

# We can use good judgement here
Style/RegexpLiteral:
  Enabled: false

# Unicode comments are useful
Style/AsciiComments:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/AlignHash:
  Enabled: false


# Cops that don't work with solidus yet
Style/FrozenStringLiteralComment:
  Enabled: false
