# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  mysql:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.1-node-browsers
      - image: circleci/mysql:5.7.25
    working_directory: &workdir ~/repo
    steps:
      - checkout
      # Restore bundle cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}
            - v1-dependencies-
      - run:
          name: Bundle Install
          command:
            bundle install --path=vendor/bundle
      # Store bundle cache
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      # Install Chrome lastest version
      - run:
         name: Install Chrome
         command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get -y install google-chrome-stable
      # Dummy app setup
      - run: bundle exec rake test_app
      # Check syntax and style
      - run: bundle exec rubocop
      # run tests!
      - run:
          name: run tests
          command: bundle exec rspec
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  postgres:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.1-node-browsers
      - image: circleci/postgres:10.7
    working_directory: &workdir ~/repo
    steps:
      - checkout
      # Restore bundle cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}
            - v1-dependencies-
      - run:
          name: Bundle Install
          command:
            bundle install --path=vendor/bundle
      # Store bundle cache
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run: sudo apt install -y postgresql-client
      # Install Chrome lastest version
      - run:
         name: Install Chrome
         command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get -y install google-chrome-stable
      # Dummy app setup
      - run: bundle exec rake test_app
      # Check syntax and style
      - run: bundle exec rubocop
      # run tests!
      - run:
          name: run tests
          command: bundle exec rspec
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  build:
    jobs:
      - mysql
      - postgres
