env:
  - SOLIDUS_BRANCH=v2.5 DB=postgres
  - SOLIDUS_BRANCH=v2.6 DB=postgres
  - SOLIDUS_BRANCH=v2.7 DB=postgres
  - SOLIDUS_BRANCH=master DB=postgres
  - SOLIDUS_BRANCH=v2.5 DB=mysql
  - SOLIDUS_BRANCH=v2.6 DB=mysql
  - SOLIDUS_BRANCH=v2.7 DB=mysql
  - SOLIDUS_BRANCH=master DB=mysql

command:
  - bundle exec rspec

