env:
  - SOLIDUS_BRANCH=v2.0 DB=postgres
  - SOLIDUS_BRANCH=v2.1 DB=postgres
  - SOLIDUS_BRANCH=v2.2 DB=postgres
  - SOLIDUS_BRANCH=v2.3 DB=postgres
  - SOLIDUS_BRANCH=v2.4 DB=postgres
  - SOLIDUS_BRANCH=v2.5 DB=postgres
  - SOLIDUS_BRANCH=v2.6 DB=postgres
  - SOLIDUS_BRANCH=v2.7 DB=postgres
  - SOLIDUS_BRANCH=master DB=postgres
  - SOLIDUS_BRANCH=v2.0 DB=mysql
  - SOLIDUS_BRANCH=v2.1 DB=mysql
  - SOLIDUS_BRANCH=v2.2 DB=mysql
  - SOLIDUS_BRANCH=v2.3 DB=mysql
  - SOLIDUS_BRANCH=v2.4 DB=mysql
  - SOLIDUS_BRANCH=v2.5 DB=mysql
  - SOLIDUS_BRANCH=v2.6 DB=mysql
  - SOLIDUS_BRANCH=v2.7 DB=mysql
  - SOLIDUS_BRANCH=master DB=mysql

command:
  - bundle exec install
  - bundle exec rspec
